[package]
name = "async-mpd"
edition = "2018"
version = "0.1.0"
authors = ["Johan Kristell <johan@jott.se>"]
keywords = ["mpd"]
license = "MIT OR Apache-2.0"
description = "Async Mpd client library"
categories = ["network-programming"]
repository = "https://github.com/jkristell/async-mpd"
readme = "README.md"

[dependencies]
async-std = { version = "1.6.0", features = ["attributes"] }
itertools = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4.8"
time = { version = "0.2", features = ["serde"] }

[dev-dependencies]
structopt = "0.3"
femme = "2.1.0"

